import Head from "next/head"
import { Header } from "./Header"



export const Layout = ({children}) => {
    return (
        <>
            <Head>
                <title>NukSend</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="bg-gray-100 min-h-screen">
                <div className="container mx-auto">
                    <Header/>
                    <main className="p-4">
                        {children}
                    </main>
                </div>
            </div>
        </>

    )
}
